apiVersion: v1
kind: Pod
metadata:
  name: deepseek-finetune
  namespace: s85468
spec:
  restartPolicy: OnFailure
  containers:
  - name: deepseek-finetune-container
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    command: ["bash", "-c", "while true; do sleep 30; done"]
    resources:
      limits:
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: my-storage-volume
      mountPath: /storage
  volumes:
  - name: my-storage-volume
    persistentVolumeClaim:
      claimName: my-storage-volume
  nodeSelector:
    kubernetes.io/hostname: cl-worker29 ## ggf wieder auf v100 wechseln!
