apiVersion: v1
kind: Pod
metadata:
  name: text2gloss-augementation
  namespace: s85468
spec:
  restartPolicy: OnFailure
  containers:
  - name: text2gloss-augementation-container
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    command: ["bash", "-c", "cd /storage/text2gloss-finetune && ./start_augment.sh"]
    resources:
      limits:
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: my-storage-volume
      mountPath: /storage
  volumes:
  - name: my-storage-volume
    persistentVolumeClaim:
      claimName: my-storage-volume
  nodeSelector:
    gpu: v100

# Start the pod and data augmentation: kubectl apply -f text2gloss-data-augmentation-pod.yml
# Delete the pod: kubectl delete -f text2gloss-data-augmentation-pod.yml

# Copy the results:
# kubectl cp s85468/mimicmotion:/storage/text2gloss-finetune/augmented_dataset.csv /Users/frederikbusch/Developer/master-arbeit/text2gloss2pose/bht-cluster/deepseek-finetuning/augmented_dataset.csv
# kubectl cp s85468/mimicmotion:/storage/text2gloss-finetune/data_augment.log /Users/frederikbusch/Developer/master-arbeit/text2gloss2pose/bht-cluster/deepseek-finetuning/data_augment.log
