apiVersion: v1
kind: Pod
metadata:
  name: mimicmotion
  namespace: s85468
spec:
  containers:
  - name: mimicmotion-container
    image: fredbln98/mimicmotion:latest
    # This command keeps the container alive so you can later exec into it.
    command: ["bash", "-c", "while true; do sleep 30; done"]
    resources:
      limits:
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: fbusch-volume
      mountPath: /storage
  volumes:
  - name: fbusch-volume
    persistentVolumeClaim:
      claimName: fbusch-volume
  # Node selector to ensure the pod is scheduled only on nodes with a V100 GPU.
  nodeSelector:
    gpu: a100
