apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbusch-volume
  namespace: s85468
spec:
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
