apiVersion: v1
kind: Pod
metadata:
  name: deepseek-finetune-kcross-val-1
  namespace: s85468
spec:
  restartPolicy: OnFailure
  containers:
  - name: deepseek-finetune-container-kcross-val-1
    image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
    command: ["bash", "-c", "cd /storage/text2gloss-finetune && ./start_finetune.sh 1 6"]
    resources:
      limits:
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: fbusch-volume
      mountPath: /storage
  volumes:
  - name: fbusch-volume
    persistentVolumeClaim:
      claimName: fbusch-volume
  nodeSelector:
    gpu: a100
    #kubernetes.io/hostname: cl-worker29
